import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {createHandler} from '../server/api.mjs';
import {authorize} from '../server/auth.mjs';
import {notifyCustomer,notifyQuote} from '../server/notifications.mjs';
import {generateKeyPair,SignJWT,exportJWK} from 'jose';
function db(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../migrations/0001_quotes.sql',import.meta.url),'utf8'));sql.exec(readFileSync(new URL('../migrations/0002_customer_receipts.sql',import.meta.url),'utf8'));return {sql,prepare(query){const create=(args=[])=>({bind(...v){return create(v);},async first(){return sql.prepare(query).get(...args)||null;},async all(){return {results:sql.prepare(query).all(...args)};},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:Number(r.changes)}};}});return create();},async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
function payload(){return {submissionId:crypto.randomUUID(),turnstileToken:'test',contact:{name:'Test Customer',company:'Example',email:'test@example.com',phone:'3175550100'},address:'Test Indianapolis',installDate:'',notes:'Test only',plan:{version:1,mode:'draw',scale:10,manual:0,runs:[{points:[[0,0],[400,0]],lengths:[100]}],gates:[{type:'single',run:0,segment:0,t:.5}],extraGates:{single:0,double:0}},options:{months:12,fence:'driven',project:'construction',screen:'none',zone:'near',shortJob:false,topRail:false,reinforce:false,asphalt:0,bags:0,locks:0,wheels:0,feet:1,single:0},price:1};}
function setup(overrides={}){const database=db(),env={QUOTES_DB:database,PUBLIC_ORIGIN:'https://test.example',ACCEPT_QUOTES:'true',TURNSTILE_SITE_KEY:'test',TURNSTILE_SECRET_KEY:'test',RECEIPT_SIGNING_KEY:'unit-test-secret-at-least-32-characters'},pending=[];const handle=createHandler({auth:async r=>{if(r.headers.get('authorization')!=='test-staff'){const {HttpError}=await import('../server/validation.mjs');throw new HttpError(401,'Unauthorized');}return 'staff@example.com';},verifyChallenge:async()=>true,notify:async()=>{},...overrides});return {database,env,async call(path,method='GET',data,extra={}){const r=await handle({env,request:new Request('https://test.example'+path,{method,headers:{Origin:'https://test.example','Content-Type':'application/json',...extra},...(data!==undefined?{body:JSON.stringify(data)}:{})}),waitUntil:p=>pending.push(p)});return {status:r.status,data:await r.json(),headers:r.headers};}};}
const staff={authorization:'test-staff'};
test('server computes price from actual geometry and gates; duplicate retry retains one ID',async()=>{const s=setup(),p=payload();const a=await s.call('/api/quotes','POST',p);assert.equal(a.status,201);const b=await s.call('/api/quotes','POST',p);assert.equal(a.data.id,b.data.id);assert.equal(s.database.sql.prepare('SELECT count(*) n FROM quotes').get().n,1);const detail=await s.call('/api/staff/quotes/'+a.data.id,'GET',undefined,staff);assert.equal(detail.data.pricing.total,560);assert(!JSON.stringify(detail.data).includes(p.submissionId));const receipt=await s.call('/api/quote-receipt','POST',{id:a.data.id,token:a.data.receiptToken});assert.equal(receipt.status,200);assert.equal(receipt.data.pricing.total,560);assert(!JSON.stringify(receipt.data).includes('test@example.com'));const wrong=await s.call('/api/quote-receipt','POST',{id:a.data.id,token:'x'.repeat(43)});assert.equal(wrong.status,404);p.notes='changed';assert.equal((await s.call('/api/quotes','POST',p)).status,409);});
test('invalid inputs, origin, disabled service, failed challenge and storage failure do not confirm success',async()=>{const s=setup();let p=payload();p.plan.gates[0].segment=20;assert.equal((await s.call('/api/quotes','POST',p)).status,400);assert.equal((await s.call('/api/quotes','POST',payload(),{Origin:'https://evil.example'})).status,403);s.env.ACCEPT_QUOTES='false';assert.equal((await s.call('/api/quotes','POST',payload())).status,503);assert.equal((await setup({verifyChallenge:async()=>false}).call('/api/quotes','POST',payload())).status,400);const broken=setup();broken.database.batch=async()=>{throw Error('private db details');};const response=await broken.call('/api/quotes','POST',payload());assert.equal(response.status,503);assert(!response.data.error.includes('private db'));});
test('staff access, search, notes, audit record and optimistic concurrency',async()=>{const s=setup(),p=payload(),a=await s.call('/api/quotes','POST',p);assert.equal((await s.call('/api/staff/quotes')).status,401);let list=await s.call('/api/staff/quotes?q=Test','GET',undefined,staff);assert.equal(list.data.quotes.length,1);assert.equal((await s.call('/api/staff/quotes?q=%25','GET',undefined,staff)).data.quotes.length,0);const path='/api/staff/quotes/'+a.data.id;const update=await s.call(path,'PATCH',{status:'contacted',internalNotes:'Private call notes',revision:1},staff);assert.equal(update.data.revision,2);assert.equal((await s.call(path,'PATCH',{status:'closed',internalNotes:'stale',revision:1},staff)).status,409);assert.equal(s.database.sql.prepare('SELECT count(*) n FROM quote_events').get().n,2);assert.equal((await s.call('/api/staff/quotes?status=new','GET',undefined,staff)).data.quotes.length,0);const receipt=await s.call('/api/quote-receipt','POST',{id:a.data.id,token:a.data.receiptToken});assert(!JSON.stringify(receipt.data).includes('Private call notes'));});
test('notification without configuration leaves a saved request and visible status',async()=>{const s=setup(),a=await s.call('/api/quotes','POST',payload()),row=s.database.sql.prepare('SELECT * FROM quotes WHERE id=?').get(a.data.id);await notifyQuote(s.env,row);assert.equal(s.database.sql.prepare('SELECT notification_status s FROM quotes').get().s,'not_configured');});
test('Access validates signatures, audience, expiry and staff allowlist; never trusts email headers',async()=>{await assert.rejects(authorize(new Request('https://test.example'),{}));const {privateKey,publicKey}=await generateKeyPair('RS256');const jwk=await exportJWK(publicKey);jwk.kid='test';jwk.alg='RS256';const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({keys:[jwk]}),{headers:{'Content-Type':'application/json'}});try{const env={ACCESS_TEAM_DOMAIN:'fw-test.cloudflareaccess.com',ACCESS_AUD:'expected',STAFF_EMAILS:'staff@example.com'};const token=async(email,aud='expected',expires='1h')=>new SignJWT({email}).setProtectedHeader({alg:'RS256',kid:'test'}).setIssuedAt().setSubject('test').setIssuer('https://fw-test.cloudflareaccess.com').setAudience(aud).setExpirationTime(expires).sign(privateKey);const request=t=>new Request('https://test.example',{headers:{'Cf-Access-Jwt-Assertion':t}});assert.equal(await authorize(request(await token('staff@example.com')),env),'staff@example.com');await assert.rejects(authorize(request(await token('other@example.com')),env));await assert.rejects(authorize(request(await token('staff@example.com','wrong')),env));await assert.rejects(authorize(request(await token('staff@example.com','expected','-1h')),env));await assert.rejects(authorize(new Request('https://test.example',{headers:{'Cf-Access-Authenticated-User-Email':'staff@example.com'}}),env));}finally{globalThis.fetch=original;}});


test('receipt expiry and staff revocation do not delete the saved record',async()=>{
 const s=setup(),p=payload(),a=await s.call('/api/quotes','POST',p);
 assert.equal(a.data.receiptToken.length,43);
 const token=a.data.receiptToken;
 const repeat=await s.call('/api/quotes','POST',p);assert.equal(repeat.data.receiptToken,token);
 assert.equal((await s.call('/api/quote-receipt','POST',{id:a.data.id,submissionId:p.submissionId})).status,404);
 const now=Date.now;try{Date.now=()=>now()+31*86400000;assert.equal((await s.call('/api/quote-receipt','POST',{id:a.data.id,token})).status,410);}finally{Date.now=now;}
 assert.equal((await s.call('/api/staff/quotes/'+a.data.id+'/revoke-receipt','POST',{},staff)).status,200);
 assert.equal((await s.call('/api/quote-receipt','POST',{id:a.data.id,token})).status,410);
 assert.equal(s.database.sql.prepare('SELECT count(*) n FROM quotes').get().n,1);
 assert.equal((await s.call('/api/quotes','POST',p)).data.receiptToken,null);
});
test('customer email has a private expiring link, retries a failure, and avoids duplicate sends',async()=>{
 const s=setup({customerNotify:async()=>{}}),a=await s.call('/api/quotes','POST',payload()),row=s.database.sql.prepare('SELECT * FROM quotes').get();
 const env={...s.env,RESEND_API_KEY:'test-only',QUOTE_NOTIFY_FROM:'test@example.com'};
 const original=globalThis.fetch;let calls=0,email;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');email=JSON.parse(options.body);calls++;return new Response('{}',{status:calls===1?503:200});};
 try{await notifyCustomer(env,row);assert.equal(s.database.sql.prepare('SELECT customer_notification_status s FROM quotes').get().s,'failed');await notifyCustomer(env,row);assert.equal(s.database.sql.prepare('SELECT customer_notification_status s FROM quotes').get().s,'accepted');await notifyCustomer(env,row);assert.equal(calls,2);assert.deepEqual(email.to,['test@example.com']);assert(email.text.includes('/quote-confirmation/#id='+a.data.id+'&token='+a.data.receiptToken));assert(email.text.includes('30 days'));assert(!email.text.includes('Internal'));}finally{globalThis.fetch=original;}
});
