from pathlib import Path
import re
R=Path(__file__).resolve().parent
s=(R/'dist/index.html').read_text(encoding='utf-8')
head=s[:s.index('<main')]
head=re.sub(r'<title>.*?</title>','<title>Plan Your Fence & Estimate | Fence Wizards</title>',head)
head=re.sub(r'<meta name="description" content="[^"]*">','<meta name="description" content="Sketch your temporary fence layout, calculate footage, and send your rental details to Fence Wizards.">',head)
head=re.sub(r'<link rel="canonical"[^>]*>','<link rel="canonical" href="https://www.fencewizards.com/estimate/">',head)
head=re.sub(r'<script type="application/ld\+json">.*?</script>','',head)
head=head.replace('</head>','<link rel="stylesheet" href="/estimator.css?v=segments-2"><script type="module" src="/estimator.js?v=segments-6"></script><link rel="stylesheet" href="/estimate-steps.css?v=compact-2"><script type="module" src="/estimate-steps.js?v=compact-2"></script></head>')
footer=s[s.index('<footer class="site-footer">'):]
body='''<main id="main" class="estimate-page">
<section class="estimate-intro wrap"><p class="eyebrow red">Fence Wizards / Project planner</p><h1>Your site. Your fence plan.</h1><p class="version-choice">Version 2 · Step-by-step planner · <a href="/estimate-original/">Compare Version 1</a></p><p>Lay out the fence, add the rental details, and send your plan to Richard.</p><div class="estimate-notice"><strong>Planner preview</strong><span>Sketch your layout and explore preliminary pricing from Richard’s rate sheet. Google satellite maps are not connected yet.</span></div></section>
<div class="wrap estimator-layout"><div class="estimator-main">
<section class="planner-card" aria-labelledby="site-heading"><div class="step-heading"><span>01</span><div><p class="eyebrow red">Location & layout</p><h2 id="site-heading">Start with the site.</h2></div></div>
<label class="est-field">Project address or city <input id="site-address" autocomplete="street-address" maxlength="300" placeholder="Street address, city, Indiana"></label><p class="est-help">Address search and satellite imagery will be available when Google Maps is connected. Entering an address here does not locate or measure the property.</p>
<div class="measure-tabs" role="group" aria-label="Measurement method"><button type="button" id="draw-mode" aria-pressed="true">Sketch a layout</button><button type="button" id="manual-mode" aria-pressed="false">Enter footage</button></div>
<div id="sketch-panel"><div class="canvas-toolbar"><label>Feet per grid square <select id="grid-scale"><option value="5">5 ft</option><option value="10" selected>10 ft</option><option value="20">20 ft</option><option value="50">50 ft</option></select></label><span>Scale sketch · not a property map</span></div>
<div class="drawing-shell"><svg id="fence-canvas" viewBox="0 0 800 500" tabindex="0" role="img" aria-label="Fence layout drawing canvas. Click or tap corners to draw. Use the segment list or manual footage option for keyboard entry." aria-describedby="drawing-help"><defs><pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="#d8ddd9" stroke-width="1"/></pattern></defs><rect width="800" height="500" fill="#f5f7f3"/><rect width="800" height="500" fill="url(#grid)"/><g id="drawing-content"></g></svg><div id="canvas-empty"><strong>Click the first corner to start.</strong><span>Each grid square represents the distance selected above.</span></div></div>
<p class="est-help" id="drawing-help">Tap corners to add fence segments. Drag a point to adjust it. Choose “New run” for a separate fence line. Known lengths can be entered below. Select a gate tool, then click a fence line to add a gate or a gate marker to remove it.</p><div class="drawing-control-groups"><div class="draw-tools" role="group" aria-label="Fence drawing controls"><button type="button" id="gate-cancel" aria-pressed="true">Draw fence</button><button id="new-run" type="button">New run</button><button id="close-run" type="button">Close run</button><button id="undo" type="button">Undo</button><button id="redo" type="button">Redo</button><button id="clear-plan" type="button">Clear drawing</button></div><div class="draw-tools gate-tools" role="group" aria-label="Gate placement controls"><button type="button" id="gate-single" aria-pressed="false">Add single gate</button><button type="button" id="gate-double" aria-pressed="false">Add double gate</button><button type="button" id="gate-remove" aria-pressed="false">Remove gate</button></div></div>
<details class="segment-details" id="segment-details"><summary>Fence segments <span id="segment-count">0 segments</span></summary><p class="est-help">Review the lengths of your drawn fence segments below. You can enter a known measurement for each segment.</p><div id="segment-list"></div></details><p id="drawing-status" class="est-help" role="status"></p></div>
<div id="manual-panel" hidden><label class="est-field">Total fence length (linear feet)<input id="manual-feet" type="number" min="1" max="100000" step="0.1" inputmode="decimal" placeholder="For example, 240"></label><p class="est-help">Enter the combined length of your fence runs. Linear feet measure the fence line, not the area inside it.</p></div>
<div class="footage-bar"><span>Total planned fence</span><strong><span id="footage-total">0</span> <small>linear ft</small></strong></div>
</section>
<section class="planner-card" aria-labelledby="rental-heading"><div class="step-heading"><span>02</span><div><p class="eyebrow red">Rental details</p><h2 id="rental-heading">Make it fit the job.</h2></div></div>
<div class="est-fields"><label class="est-field">Project type<select id="project-type"><option value="construction">Construction</option><option value="event">Event</option><option value="emergency">Emergency / restoration</option><option value="other">Other / not sure</option></select></label><label class="est-field">Fence type<select id="fence-type"><option value="panels">Panels & stands</option><option value="driven">Post-driven chain link</option><option value="barricades">Crowd-control barricades</option><option value="mixed">Combination / help me choose</option></select></label><label class="est-field">Single gates<input id="single-gates" required type="number" min="0" max="100" step="1" value="0"></label><label class="est-field">Double gates<input id="double-gates" required type="number" min="0" max="100" step="1" value="0"></label><label class="est-field">Windscreen<select id="screen-type"><option value="none">No screen</option><option value="plain">Plain windscreen</option><option value="printed">Printed windscreen</option><option value="unsure">Not sure yet</option></select></label><label class="est-field">Preferred installation date<input id="install-date" type="date"></label><label class="est-field">Rental duration (months)<input id="rental-months" type="number" min="1" max="60" step="1" value="12"></label><label class="est-field">Approximate distance from Indianapolis<select id="delivery-zone"><option value="unknown">Not sure — Richard to confirm</option><option value="near">Under 50 miles</option><option value="far">50 miles or more</option></select></label></div>
<p class="est-help" id="gate-pricing"></p><p class="est-help">Gate totals update as you add or remove gates on the drawing. You can increase these totals for gates you have not placed yet. To remove a drawn gate, choose “Remove gate” and click its marker. Gate markers do not subtract footage; Richard will confirm opening sizes and final measurements.</p><label class="est-check"><input id="short-job" type="checkbox">Short event or short-term discount requested</label><p class="est-help">Rates cover the rental term, not a monthly charge. Distance is self-reported until maps are connected. Richard confirms service coverage and all final pricing.</p>
<details class="estimate-addons"><summary>Additional equipment & site conditions</summary><div class="est-fields"><label class="est-check" data-for="driven"><input id="top-rail" type="checkbox">Top rail</label><label class="est-field" data-for="driven">Posts through asphalt<input id="asphalt-posts" type="number" min="0" max="10000" value="0"></label><label class="est-check" data-for="panels"><input id="reinforce" type="checkbox">Posts every other panel</label><label class="est-field" data-for="panels">Additional sandbags (total)<input id="extra-bags" type="number" min="0" max="10000" value="0"></label><label class="est-field">Chain & lock sets<input id="lock-count" type="number" min="0" max="100" value="0"></label><label class="est-field">Gate wheels<input id="wheel-count" type="number" min="0" max="100" value="0"></label></div><p class="est-help">One sandbag per stand and standard panel gates are included in panel rates. Additional windscreen ballast must be confirmed. Specialty heights, extra-large gates, prevailing-wage work, and modifications require a custom quote.</p></details>
<label class="est-field">Site access, gate sizes, and anything else we should know<textarea id="project-notes" rows="3" maxlength="3000" placeholder="Paved ground, a delivery entrance, pickup timing, or questions for Richard…"></textarea></label><p class="est-help">Windscreen is purchased and stays yours after fence removal. Richard will confirm fence height, gates, access, and scheduling.</p>
</section>
<section class="planner-card" aria-labelledby="send-heading"><div class="step-heading"><span>03</span><div><p class="eyebrow red">Send your plan</p><h2 id="send-heading">Let’s work out the details.</h2></div></div><div class="send-plan-summary" id="send-plan-summary" aria-live="polite"></div><form id="estimate-form"><div class="est-fields"><label class="est-field">Your name *<input name="name" autocomplete="name" maxlength="150" required></label><label class="est-field">Company<input name="company" autocomplete="organization" maxlength="180"></label><label class="est-field">Email *<input name="email" type="email" autocomplete="email" maxlength="200" required></label><label class="est-field">Phone *<input name="phone" type="tel" autocomplete="tel" maxlength="40" required></label></div><input class="bot-field" type="checkbox" name="botcheck" tabindex="-1" aria-hidden="true"><p class="est-help">Once submissions are connected, your contact details, project information, and fence layout will be saved with your request for Richard to review. <a href="/privacy/">Privacy Policy</a>.</p><button class="button" type="submit">Send my plan for a quote ↗</button><p class="est-help"><span id="quote-mode-note">Quote requests will be saved after Cloudflare is connected.</span></p><div id="quote-demo-links" hidden><p class="est-help">Design examples only. These do not save or send your details.</p><a href="/quote-confirmation/?demo=1">View sample confirmation</a> · <a href="/staff/quotes/?demo=1">View sample quote inbox</a></div><p id="send-status" role="status" tabindex="-1"></p></form></section>
</div>
<aside class="estimate-sidebar"><div class="estimate-summary"><p class="eyebrow red">Your project at a glance</p><h2>Fence plan</h2><dl><div><dt>Footage</dt><dd id="summary-feet">Not entered</dd></div><div><dt>Fence</dt><dd id="summary-fence">Panels & stands</dd></div><div><dt>Rental</dt><dd id="summary-term">Not selected</dd></div><div><dt>Gates</dt><dd id="summary-gates">0</dd></div><div><dt>Screen</dt><dd id="summary-screen">No screen</dd></div></dl><div class="price-result"><span>Estimated total</span><strong id="price-total">Add your footage</strong><p id="price-explanation">Enter your fence length to see preliminary pricing.</p></div><div id="price-items"></div><ul id="price-review"></ul><p class="est-help">Before tax. Planning estimate only; Richard confirms measurements, site conditions, delivery, minimum charges, and availability. Not a booking or binding quote.</p><p class="summary-inclusions">Delivery, installation & removal<br>Included in Richard’s project quote.</p><a class="button" href="#send-heading">Request this quote ↗</a><a class="est-call" href="tel:+13172964015">Questions? (317) 296-4015</a><div class="plan-files"><button id="save-plan" type="button">Save plan file</button><label>Load plan file<input id="load-plan" type="file" accept=".json,application/json"></label><button id="print-plan" type="button">Print plan</button></div><p class="est-help">Saved files contain the layout and rental selections, without contact details or the site address. Sketch measurements depend on the scale and lengths you enter.</p></div></aside></div></main>'''
out=R/'dist/estimate/index.html';out.parent.mkdir(exist_ok=True);out.write_text(head+body+footer,encoding='utf-8')
# Replace the former provider entry points with the native planner.
for p in (R/'dist').rglob('*.html'):
 text=p.read_text(encoding='utf-8')
 text=re.sub(r'/site.js\?v=[^\"]+', '/site.js?v=estimator-1', text)
 text=re.sub(r'<button class="([^"]*)" data-plotquote>.*?</button>',lambda m:'<a class="'+m[1]+'" href="/estimate/">'+('Plan your fence online ↗' if 'plot-link' in m[1] else 'Open the fence planner ↗')+'</a>',text,flags=re.S)
 text=text.replace('Our PlotQuote tool is coming soon. In the meantime, this form gets your project started.','Sketch your fence layout, enter known measurements, and explore preliminary pricing in our project planner.')
 text=text.replace('Is PlotQuote available?','Can I plan my fence online?').replace('Not yet. The online estimate tool is coming soon. Use the contact form or call Richard for a project quote.','Yes. Our fence planner lets you sketch a layout or enter footage and request a quote. Satellite maps are still being connected.')
 p.write_text(text,encoding='utf-8')

import runpy
runpy.run_path(str(R/'build-quote-pages.py'))

runpy.run_path(str(R/'build-ctas.py'))

runpy.run_path(str(R/'build-privacy.py'))
