const {chromium}=require('C:/Users/gsvpr/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
(async()=>{fs.mkdirSync('qa',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks=[];
for(const route of ['/','/contact/']){await page.goto('http://127.0.0.1:8765'+route);await page.waitForLoadState('networkidle');await page.locator('img').evaluateAll(images=>images.forEach(i=>i.loading='eager'));await page.waitForFunction(()=>[...document.images].every(i=>i.complete));checks.push({route,title:await page.title(),h1:await page.locator('h1').count(),form:await page.locator('form').count(),missingImages:await page.locator('img').evaluateAll(images=>images.filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.src)),overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});await page.screenshot({path:`qa/${route==='/'?'home':'contact'}-desktop.png`,fullPage:true});}
await page.goto('http://127.0.0.1:8765/contact/?project=Construction');if(await page.locator('[name=project_type]').inputValue()!=='Construction')throw Error('Project prefill failed');
await page.locator('[data-plotquote]').click();if(!await page.locator('dialog').isVisible())throw Error('Dialog failed');await page.keyboard.press('Escape');
let posts=0;let payload;await page.route('https://api.web3forms.com/submit',async route=>{posts++;payload=route.request().postDataJSON();await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:true})});});
await page.locator('[type=submit]').click();if(posts)throw Error('Empty form submitted');
async function fill(){await page.locator('[name=name]').fill('Preview QA');await page.locator('[name=email]').fill('preview@example.com');await page.locator('[name=phone]').fill('3175550100');await page.locator('[name=project_location]').fill('Indianapolis');await page.locator('[name=project_type]').selectOption('Construction');}
await fill();await page.locator('[type=submit]').click();await page.locator('.form-status.success').waitFor();if(posts!==1||payload.project_location!=='Indianapolis'||!payload.subject.includes('preview test'))throw Error('Submission payload failed');checks.push({formSuccess:'passed (mocked; no email sent)'});
await page.unroute('https://api.web3forms.com/submit');await page.route('https://api.web3forms.com/submit',route=>route.fulfill({status:500,contentType:'application/json',body:'{"success":false}'}));await fill();await page.locator('[type=submit]').click();await page.locator('.form-status.error').waitFor();if(await page.locator('[name=name]').inputValue()!=='Preview QA')throw Error('Form data lost on error');checks.push({formFailure:'passed; entered details preserved'});
await page.setViewportSize({width:390,height:844});for(const route of ['/','/contact/']){await page.goto('http://127.0.0.1:8765'+route);await page.waitForLoadState('networkidle');await page.locator('img').evaluateAll(images=>images.forEach(i=>i.loading='eager'));await page.waitForFunction(()=>[...document.images].every(i=>i.complete));if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow '+route);await page.screenshot({path:`qa/${route==='/'?'home':'contact'}-mobile.png`,fullPage:true});}await page.locator('.menu-toggle').click();if(!await page.locator('#main-nav').isVisible())throw Error('Mobile menu failed');
await page.emulateMedia({reducedMotion:'reduce'});await page.goto('http://127.0.0.1:8765/');if(!await page.locator('video').evaluate(v=>v.paused))throw Error('Reduced motion failed');checks.push({mobile:'passed',reducedMotion:'passed'});
// Validate the optional agent adapter through a mock registry; native browser support is unavailable.
await page.addInitScript(()=>{Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.registeredTool=t;}}});});await page.goto('http://127.0.0.1:8765/contact/');const toolResult=await page.evaluate(async()=>{const tool=window.registeredTool;if(!tool)throw Error('Tool not registered');const result=await tool.execute({name:'Staged name',project_type:'Event'});let rejected=false;try{await tool.execute({name:'Should not change',project_type:'Invalid'});}catch{rejected=true;}return {result,rejected,name:document.querySelector('[name=name]').value};});if(!toolResult.rejected||toolResult.name!=='Staged name'||toolResult.result.submitted)throw Error('Agent adapter validation failed');checks.push({agentAdapter:'passed with mock registry; native WebMCP unavailable'});
if(errors.length)throw Error(JSON.stringify(errors));fs.writeFileSync('qa/results.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors}));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
