from pathlib import Path
p=Path(__file__).resolve().parent/'dist'
home=(p/'index.html').read_text(encoding='utf-8')
header=home.split('<main id="main">')[0]
header=header.replace('Temporary Fence Rental in Indianapolis | Fence Wizards','Request a Fence Rental Quote | Fence Wizards')
header=header.replace('Family-owned temporary fence rental for construction, events and emergency response across Indianapolis and central Indiana. Request a quote from Richard.','Tell Richard about your temporary fencing project. Request a quote for construction, events, or emergency fencing in central Indiana.')
header=header.replace('content="Fence Wizards | Temporary Fence Rental"','content="Request a Quote | Fence Wizards"').replace('content="Family-owned. Straightforward pricing. Temporary fencing across central Indiana."','content="Tell Richard where you need fencing and request a project quote."').replace('content="https://fence-wizards-design-preview.omniring09.chatgpt.site/"','content="https://fence-wizards-design-preview.omniring09.chatgpt.site/contact/"')
body='''<main id="main" class="contact-page"><div class="wrap"><div class="breadcrumb"><a href="/">Home</a> / Request a quote</div><div class="contact-grid"><div class="contact-intro"><p class="eyebrow red">Your project starts here</p><h1>Tell Richard<br>what you need.</h1><p>Construction site, upcoming event, or an urgent perimeter—send the details you have. We’ll work through the rest with you.</p><ol class="next-steps"><li>Share your location and project details.</li><li>Richard follows up to discuss the fencing and schedule.</li><li>You get a quote with installation and removal included.</li></ol><div class="contact-person"><strong>Need fencing urgently? Call Richard.</strong><a href="tel:+13172964015">(317) 296-4015</a><span>7:30 a.m.–9 p.m. · Seven days a week</span><a class="email" href="mailto:richard@fencewizards.com">richard@fencewizards.com</a></div><div class="quote-alternative"><strong>Prefer an online estimate?</strong><p>Our PlotQuote tool is coming soon. In the meantime, this form gets your project started.</p><button class="link-button" data-plotquote>About the online quote tool</button></div></div><div data-form-host></div></div></div></main><div data-footer></div><div data-plot-dialog></div></body></html>'''
(p/'contact/index.html').write_text(header+body,encoding='utf-8')
print('Contact page written.')
