"""Reviewed copy adapted from the supplied website scrape; no invented job stories."""
PAGES = {}
def add(path, title, intro, image, sections, *, kind='service', facts=None, faq=None, related=None):
    PAGES[path] = dict(title=title,intro=intro,image=image,sections=sections,kind=kind,facts=facts or [],faq=faq or [],related=related or [])

add('/construction-fencing/', 'Construction Fence Rental in Indianapolis',
    'Temporary fencing for contractors who need a price, an installation date, and room to keep working. We install panels, post-driven chain link, gates, and windscreen across central Indiana.', 'construction.jpg', [
    ('Plan the perimeter around the work', ['Tell us where deliveries enter, where equipment will move, and which sides of the site meet a sidewalk or neighboring business. We use those details to plan the run and gate locations before installation.', 'For a phased project, panels and stands make it easier to change the layout. A post-driven perimeter suits longer projects where the boundary will stay in place. Both can be combined with windscreen.']),
    ('Service when the layout changes', ['A gate that worked during earthwork may be in the way during the next phase. Call Richard when a run needs extending or an access point needs moving. General contractors receive same-day service for changes on an existing job.', 'Your crew can move individual portable panels. Larger relocations and changes to post-driven fencing need a crew visit.']),
    ('A quote your estimator can use', ['Send the site address, approximate footage, fence type, number of gates, and rental duration. Richard can give you a verbal quote on the phone, followed by a written proposal.', 'The flat fee covers delivery, installation, the agreed rental term, and removal. Standard rentals run up to 12 months, with discounts for short jobs.'])],
    facts=[('Typical installation','24–48 hours'),('Contractor service','Same-day site changes'),('Standard rental','Up to 12 months')],
    faq=[('Can you fence a paved site?','Yes. Panels sit in sandbagged stands above the surface, so they can be used on asphalt and concrete.'),('Are eight-foot fences available?','Yes, in panels and post-driven chain link. Mention the height when you request a quote so Richard can confirm availability.'),('Can we add windscreen later?','Yes. Plain or printed windscreen can be fitted to a run. It is sold separately and stays yours when the rental fence is removed.')],
    related=['/fence/panels-and-stands/','/fence/post-driven-chain-link/','/fence/windscreen/'])
add('/event-fencing/','Event Fence & Barricade Rental',
    'Fencing for festivals, municipal events, corporate functions, and venues. We plan installation and pickup around load-in, opening, and load-out.', 'events.jpg', [
    ('Start with the event footprint', ['Mark the public entrances, vendor areas, queues, backstage areas, and vehicle access on your plan. Panels can enclose the overall footprint, while barricades guide queues and separate activity areas.', 'Barricades are available on their own. You do not need to rent a full fence perimeter to order them.']),
    ('Work to the production schedule', ['Tell Richard when the site becomes available, when doors open, and when the venue needs the space clear. We can set up overnight or before dawn and remove the fencing when the event ends.', 'Removal is included in the agreed quote. Share changes to the schedule so the crew and truck can be planned around them.']),
    ('Make use of the perimeter', ['Windscreen can screen a service area or provide a surface for sponsor graphics. It comes plain or custom printed and is sold, not rented.', 'Our fencing has been used at sites including the NBA All Star Game Google Pixel Event, the Final Four, and White River State Park. These are project locations; the venues were not necessarily our direct customers.'])],
    facts=[('Setup & pickup','On your event schedule'),('Options','Panels, screen & barricades'),('Removal','Included in the quote')],
    faq=[('Can you remove fencing the night an event ends?','Yes. Include the load-out time when you request the quote so pickup can be scheduled.'),('Can our sponsors appear on the fence?','Yes. Custom printed windscreen can carry sponsor graphics. Send the artwork requirements and event date when planning the order.'),('What do you need to quote an event?','The location, event footprint, approximate fence or queue length, access points, and times for load-in, opening, and load-out.')],
    related=['/fence/barricades/','/fence/panels-and-stands/','/fence/windscreen/'])
add('/emergency-fencing/','Emergency & Restoration Fencing',
    'Temporary perimeters for commercial properties after storms, fires, vehicle damage, or an unexpected loss of access control. Tell Richard where the site is and what needs to be closed off.', 'windscreen.jpg', [
    ('Get a clear answer on timing', ['Call with the address, a description of the damage, and any access restrictions. Emergency scheduling depends on the location, current work, and equipment available. Richard will discuss what can be installed and when.', 'The usual installation window is 24–48 hours. Emergency work can move faster; confirm the actual arrival time on the call.']),
    ('Choose fencing for the next stage', ['Panels and stands can establish a temporary boundary quickly and move as the restoration work develops. A post-driven line may suit a longer closure where the perimeter needs to remain in place.', 'Windscreen can reduce the view into the property while cleanup and restoration are underway. Let Richard know if adjusters, inspectors, or equipment need separate access.']),
    ('Keep the restoration team moving', ['Plan gates around the vehicles that need to enter, including debris removal and equipment deliveries. A useful perimeter leaves the restoration crew access to the work.', 'We carry umbrella, general liability, commercial auto, and workers compensation insurance. Ask Richard about certificates required for your project.'])],
    facts=[('Urgent work','Call to confirm timing'),('Contact','Richard, the owner'),('Quote','Installation & removal included')],
    faq=[('Do I need exact measurements before calling?','No. Start with the address and a description of the area. Approximate dimensions and access details help Richard plan the response.'),('Can the fence stay during a longer restoration?','Yes. Standard rentals cover up to 12 months for the agreed term. Discuss an extension before that term ends.'),('Do you repair the damaged permanent fence?','No. Fence Wizards provides temporary fence rental. Permanent fence repairs are outside our services.')],
    related=['/fence/panels-and-stands/','/fence/post-driven-chain-link/','/contact/'])

add('/fence/panels-and-stands/','Temporary Fence Panels & Stands',
    'A portable fence for changing construction sites, event footprints, and short-notice enclosures. Panels stand above the ground in bases weighted with sandbags.', 'panels.jpg',[
    ('Portable as the site changes',['Panels are useful where access points move during a job. Your crew can shift individual sections by hand, and Fence Wizards can relocate larger runs. General contractors receive same-day service for site changes.','They also work on paved lots, plazas, and concrete where driving a post is not suitable.']),
    ('Plan gates and screen together',['Pedestrian and drive gates can be included in the run. Tell us where deliveries arrive and what needs to pass through.','Windscreen can be added for privacy, dust control, or printed graphics. Screen changes the wind load on the fence, so include it in the plan from the start when possible.']),
    ('When to consider post-driven fencing',['Portable panels are designed to move. For a long-term boundary where that portability is a drawback, ask about post-driven chain link. Ground conditions, access, and the length of the project help determine the better fit.'])],kind='product',
    facts=[('Height','6 ft standard; 8 ft available'),('Installation','Stands weighted with sandbags'),('Gates','Pedestrian & vehicle access'),('Windscreen','Plain or printed; sold separately')],
    faq=[('How soon can you set panels?','Panels are our quickest system to install, with same- or next-day setup possible on many jobs. The normal overall installation window is 24–48 hours; confirm your date with Richard.'),('Can panels be used on asphalt?','Yes. They sit in stands without driven posts.'),('What affects stability in wind?','The location, weighting, and whether windscreen is fitted all matter. Discuss the site and screen requirements when quoting.')],related=['/construction-fencing/','/event-fencing/','/fence/post-driven-chain-link/'])
add('/fence/post-driven-chain-link/','Post-Driven Chain Link Fence Rental',
    'A fixed temporary perimeter for commercial construction, long-term site closures, and material storage. Posts are driven into the ground and the chain link is hung and tensioned along the run.', 'chain-link.jpg',[
    ('For a boundary that stays in place',['A driven line is harder to move than freestanding panels. It is useful on longer projects where the main perimeter is expected to remain in the same position.','Moving a gate or relocating this system requires a crew visit. Plan the delivery entrance and other access points before installation.']),
    ('The ground is part of the decision',['The site needs ground that can accept driven posts. Rock, heavy fill, and underground utilities affect the plan and installation. Tell Richard what is known about the surface and ground before the crew arrives.','Where posts are unsuitable, panels and stands offer an above-ground alternative.']),
    ('Removal and the surface afterwards',['Removal is included in the agreed quote, including pulling the temporary posts. Driven posts can leave marks or holes; this is not a landscaping service. If protecting a finished surface is important, discuss panels instead.'])],kind='product',
    facts=[('Height','6 ft standard; 8 ft available'),('Installation','Driven posts & tensioned chain link'),('Changes','Crew visit required'),('Best suited to','Longer, fixed perimeters')],
    faq=[('Can we include gates?','Yes. Both pedestrian and drive gates can be built into the line.'),('Does it take longer to install than panels?','Yes. Driving posts and hanging the fabric require additional installation work. Richard schedules this around the site and length of the run.'),('Can we add privacy screen?','Yes. Plain or custom printed windscreen can be fitted. It is sold separately from the fence rental.')],related=['/construction-fencing/','/fence/panels-and-stands/','/fence/windscreen/'])
add('/fence/windscreen/','Windscreen & Printed Fence Screen',
    'Screen for privacy, dust control, and a finished street-facing perimeter. Choose plain fabric or custom graphics for a construction site, event, or restoration project.', 'printed-screen.jpg',[
    ('Plain screen for the working perimeter',['Windscreen fits across temporary panels or post-driven chain link. It reduces the view into the site and helps limit dust leaving the perimeter.','Screen is an addition to the fence, not a replacement for other site dust-control measures. Discuss the exposure and ground conditions with Richard.']),
    ('Your graphics along the fence',['Custom screen can carry a company logo, sponsor graphics, a development rendering, or a leasing message. It makes use of a surface already visible from the street or event grounds.','Include the print area, artwork, fence height, and required date when asking for a quote.']),
    ('Sold, not rented',['Windscreen stays yours after the fence comes down. Its price is separate from the rental fence terms.','Adding screen increases wind load. The supporting fence and weighting need to account for it, including when screen is added to an existing run.'])],kind='product',
    facts=[('Terms','Sold, not rented'),('Styles','Plain or custom printed'),('Fits','Panels & post-driven fencing'),('Planning','Allow for added wind load')],
    faq=[('Can screen be added later?','Yes. Tell Richard about the fence already in place and the area to be screened.'),('Can it go on another company’s fence?','Ask Richard. Fit and support depend on the existing fence, so it needs to be assessed.'),('Do we keep the printed screen?','Yes. Both plain and printed screen are sold and remain yours.')],related=['/fence/panels-and-stands/','/event-fencing/','/construction-fencing/'])
add('/fence/barricades/','Crowd-Control Barricade Rental',
    'Interlocking steel barricades for entrances, queue lines, event areas, and venue interiors. We position them to your plan and work to your production schedule.', 'barricades.jpg',[
    ('Set the line where people need it',['Use barricades to organize entry queues, outline beverage areas, or guide people through a temporary event layout. Share the expected route and where crossings are needed.','Tell Richard the approximate length of the line rather than trying to calculate a barricade count.']),
    ('Available on their own or with fencing',['You can rent barricades without a panel fence. For larger events, combine them with perimeter panels and windscreen to handle different parts of the same site.','We supply steel barricades for indoor and outdoor use. We do not supply stanchions.']),
    ('Setup and pickup on your schedule',['Provide the load-in, opening, and load-out times. We can work overnight or before dawn and remove the barricades when the event ends.','The standard installation window is 24–48 hours. Call with urgent event dates to discuss availability.'])],kind='product',
    facts=[('Type','Interlocking steel'),('Placement','Positioned to your plan'),('Use','Indoor & outdoor events'),('Order','Standalone or with fence rental')],
    faq=[('Do you just drop off a stack?','No. The barricades are positioned to the agreed plan.'),('Can we rent only barricades?','Yes. Send the location, approximate length, and schedule.'),('Can pickup happen after an evening event?','Yes. Include the load-out time so it can be part of the agreed schedule.')],related=['/event-fencing/','/fence/panels-and-stands/','/pricing/'])

add('/pricing/','Temporary Fence Rental Pricing',
    'One flat fee for the agreed rental term, with delivery, installation, and final removal included. Start with an online estimate, then confirm the scope and price with Richard.', None,[
    ('Local ownership. Lower prices.',['Fence Wizards is a smaller, family-owned business. Buying material directly and running our own crew helps us keep prices competitive with large national rental companies.','Send a comparable written quote if you have one. Richard can look at the scope and tell you how our price compares.']),
    ('What goes into your quote',['The site address, fence type, linear footage, gates, and rental duration determine the starting price. Windscreen, extra ballast, asphalt posts, and other accessories can add to it. Ground conditions, access, and timing also affect the work involved.','New installations 50 miles or more outside Indianapolis carry a $1-per-linear-foot surcharge on the current price sheet. Richard needs to confirm how that distance is measured. If the distance is unknown, the online estimate leaves that surcharge out and flags it for review.']),
    ('What the flat fee covers',['Delivery, installation, rental for the agreed term, and final removal are included in the project quote. The current base pricing covers up to 12 months for panels and stands, and up to 18 months for post-driven fencing. Longer rentals have separate rate bands.','A delay within the agreed term does not start a monthly rent charge. If the job will run beyond that term, contact Richard before it ends. Ask about short-job and event discounts; Richard confirms the amount for your project.']),
    ('Gates, screen, and changes to the layout',['Standard gates are included with panels and stands. For post-driven fencing, the current sheet lists single gates at $140 and double gates at $280. Extra-wide fabricated gates, gate wheels, and chains and locks are priced separately.','Plain and printed windscreen are purchased, not rented. Screened panels may need additional ballast; Richard will confirm the stand count and sandbags required. Moving fencing or adding gates after installation is a change to the original scope and can involve separate labor and call-out charges.']),
    ('An estimate first. A confirmed quote next.',['The online planner uses your footage and selections to show a preliminary, pre-tax estimate. It is not a confirmed booking or final price. Richard reviews the site, schedule, accessories, and any items flagged for confirmation before you agree to the work.','Some rental durations and specialty requests need a custom quote. Tax and any minimum charge for a new installation still need confirmation and are not included in the planner. Emergency work and changes to an existing installation are reviewed separately.']),
    ('Payment and proposals',['Richard can quote verbally on the phone, followed by a written proposal. Net 30 is available for vetted accounts and established clients. Smaller or unvetted accounts pay up front; the applicable terms are discussed at the start.','Damaged equipment can carry replacement or repair charges, as listed on the price sheet. Ask Richard about those terms and the optional damage waiver before agreeing to the rental; the waiver is not included automatically.'])],kind='information',
    facts=[('Rental term','Agreed up front'),('Online pricing','Preliminary estimate'),('Final removal','Included'),('Established accounts','Net 30 available')],
    faq=[('Do you price fencing by the foot?','Yes. Fence type, footage, and rental duration set the base price. Gates, accessories, distance, and site requirements can change the total. The agreed quote covers the complete scope.'),('Is windscreen a rental?','No. Plain and custom printed windscreen are sold and stay yours.'),('Can I plan my fence online?','Yes. Sketch your fence layout or enter known footage to explore preliminary pricing. This preview does not yet include Google Maps or online quote submission. Contact Richard to request a confirmed quote.')],related=['/estimate/','/contact/','/faq/','/fence/panels-and-stands/'])
add('/about/','Three Generations of Fencing',
    'Fence Wizards is a family business based in Greenwood, Indiana. Richard Warren runs the company with his father and brother, serving contractors, event organizers, and businesses across central Indiana.', 'family.jpg',[
    ('Experience on the crew',['Richard is a third-generation fencer. More than ten years of permanent fencing experience informs the temporary installations the family handles today.','The business invests in current installation equipment to help the crew work efficiently. The trucks and fencing belong to Fence Wizards, and material is purchased directly from manufacturers.']),
    ('A working relationship with the owner',['Richard handles quotes and service calls. He stays involved when a layout changes, a gate needs moving, or the fence is ready for pickup.','The aim is to be a dependable contact for the next project as well as this one. Flat-fee quotes, included removal, and same-day service for general contractors are part of that approach.']),
    ('Insurance and project requirements',['We carry umbrella, general liability, commercial auto, and workers compensation insurance. Ask Richard for the certificates your project requires.','Fence Wizards was named in Where To Get Stuff Fixed in 2023.']),
    ('Sites where our fencing has been used',['Our fencing has been on sites including the NBA All Star Game Google Pixel Event, the Final Four, Ball State University, Veterans Affairs, the Social Security Administration, and White River State Park.','These names identify project locations and end users. They do not imply that each venue or institution hired Fence Wizards directly.']),
    ('Focused on temporary fencing',['We supply temporary fence rentals, windscreen, and crowd-control barricades. We do not offer permanent fence installation, residential fencing, repairs, gate automation, stanchions, orange fencing, or fence material sales.'])],kind='information',related=['/construction-fencing/','/event-fencing/','/contact/'])

FAQ_GROUPS=[('Pricing & payment',[
('What information do you need for a quote?','The project location, fence type, approximate linear footage, gates, and rental duration. Rough measurements are fine for the first conversation.'),
('Do you charge monthly rent?','The quote is a flat fee for the agreed term. Standard rentals cover up to 12 months, and short jobs receive discounted pricing.'),
('Does the quote include removal?','Yes. Delivery, installation, and removal are included in the quote.'),
('What if the project takes longer?','A schedule slip within the agreed term does not change the rental price. Call before the term ends if you need an extension. Changes in scope should be discussed with Richard.'),
('What are the payment terms?','Established and vetted accounts can use Net 30. Smaller or unvetted accounts pay up front. Richard confirms which applies at the start.'),
('Are there damage fees?','Fence Wizards does not charge excessive damage fees. Tell Richard about damage so he can discuss the work required.'),
('How quickly can I get a price?','Richard can provide a verbal quote on the phone when the project details are available. A written proposal follows.')]),
('Installation & service',[
('How soon can you install?','The normal installation window is 24–48 hours. Confirm the date with Richard, especially for an urgent job.'),
('Do you handle emergency fencing?','Yes. Call with the location and situation. Timing depends on the site, current jobs, and available equipment.'),
('Can you work overnight for an event?','Yes. Setup and pickup can follow your load-in and load-out schedule, including overnight or before dawn.'),
('Can a gate or fence run be moved?','Yes. General contractors receive same-day service for changes on existing sites. Your crew can also move individual portable panels.'),
('Who installs the fence?','Our own crew. Richard works with his father and brother, using the company’s trucks and material.'),
('When can I call?','7:30 a.m. to 9 p.m., seven days a week. Richard handles the calls.')]),
('Fence types & site conditions',[
('What is the difference between panels and driven fencing?','Panels sit in weighted stands and can move as the layout changes. Post-driven chain link uses posts driven into the ground for a more fixed perimeter.'),
('Do you have eight-foot fencing?','Yes, in both systems. Request it early so availability can be confirmed.'),
('Can you install on concrete or asphalt?','Panels and stands work above the ground, making them suitable for paved sites.'),
('Do you provide pedestrian and drive gates?','Yes. Tell us where people and deliveries need access.'),
('Is windscreen rented or sold?','Sold. Plain and printed windscreen remain yours after the rental fence comes down.'),
('Can you print our company logo or sponsor graphics?','Yes. Discuss the artwork, dimensions, and deadline when requesting the quote.'),
('Can we rent barricades without fencing?','Yes. Barricades are available as a separate rental for indoor or outdoor events.')]),
('Coverage & the business',[
('Where do you work?','The Indianapolis metro and roughly 80 miles around downtown Indianapolis, from our base in Greenwood. Check the service-area pages or send your project address.'),
('Does distance affect the quote?','Yes. Travel to sites near the edge of the coverage area is accounted for in the quote and discussed with you.'),
('What if we are outside the listed area?','Call with the address. Richard can tell you whether the job can be served.'),
('Are you insured?','Yes. Coverage includes umbrella, general liability, commercial auto, and workers compensation. Ask for certificates needed for your project.'),
('Do you install residential or permanent fencing?','No. Fence Wizards focuses on temporary fencing for commercial construction, events, and restoration. Permanent installation, repairs, gate automation, and residential fencing are not offered.'),
('Who will handle my inquiry?','Richard Warren, the owner.')])]

# Each city keeps its own site-planning context from the original scrape.
# Landmarks are context, never represented as clients or photographed jobs.
CITIES={
'indianapolis':('Indianapolis','Downtown access, construction, and event schedules','Downtown construction often meets an active sidewalk. A useful fence plan leaves room for pedestrian routes, delivery access, and the work itself. Tell Richard which entrances must stay open and where trucks can unload.','Planning a downtown perimeter','For a frontage near the Mile Square or canal, windscreen can reduce the view into the site. Panels suit changing access points; a driven line can serve a longer fixed boundary. Gate placement needs to account for the vehicles actually using it.','Events and load-out','For events around the convention corridor and other downtown venues, include the load-in and load-out windows. We can install overnight and remove the fencing when the event ends. Barricades can be ordered separately for queues and entrances.'),
'fishers':('Fishers','Fencing beside active streets and pedestrian routes','A project near the Nickel Plate District may sit next to shops, apartments, and people walking through the area. Share the public routes and work boundaries so the fencing can be planned around them.','Where the site meets a trail or sidewalk','Identify which side of the perimeter the public uses, where deliveries cross, and which access points change during construction. Panels and windscreen can suit a changing frontage; a fixed boundary may call for post-driven chain link.','Event setup on a defined schedule','For an event in Fishers, send the footprint and opening and pickup times. Barricades can guide entry queues, while panels enclose the site. The crew can work to overnight or early-morning production windows.'),
'carmel':('Carmel','Screened frontages and longer commercial projects','Commercial and multi-family projects in Carmel can run beside open businesses and busy pedestrian areas. A fence plan needs to account for access and how the perimeter meets the street.','Screening a visible work area','For street-facing sites around Range Line Road or the Arts and Design District, windscreen can provide privacy and space for project graphics. Plain and printed screen are sold and stay yours after fence removal.','A perimeter that fits the build phases','A driven line may suit the fixed sides of a longer project. Portable panels can serve the portions where deliveries or trade access change. Explain the phases to Richard so the two systems can be considered together.'),
'noblesville':('Noblesville','Construction corridors, downtown work, and outdoor events','Noblesville projects range from long construction boundaries to short event footprints. The length of the rental and the location of access points help decide the fencing system.','Access along a construction run','For a corridor site, mark where equipment needs to enter and where the public route is planned. Gate placement and ground conditions need to be established before choosing a driven line or portable panels.','Downtown and event footprints','Work around the courthouse square or Federal Hill Commons needs a clear plan for pedestrian access. For an event elsewhere in the city, send the vendor, queue, and service areas together with load-in and load-out times. These locations describe planning contexts, not a list of our clients.'),
'bloomington':('Bloomington','Campus-adjacent work, access, and changing ground conditions','On Bloomington projects near Indiana University or other busy public areas, pedestrian activity is part of the fence plan. Tell us which edges face a walkway and where crews and deliveries need access.','Check the ground before choosing a system','Rock, slopes, and paved surfaces can affect whether posts can be driven. Share what you know about the site. Panels in weighted stands offer an above-ground option where driving posts is unsuitable.','Fixed boundaries and changing entrances','A longer project may need a driven perimeter on some sides and portable panels where access changes. Gates should match the vehicles using them and the public routes around the work. We serve Bloomington from Greenwood; include the full address when requesting timing and pricing.'),
'anderson':('Anderson','Demolition, redevelopment, and longer site closures','Temporary fencing in Anderson can serve demolition, commercial redevelopment, and properties waiting for the next phase of work. Start with the area to be enclosed and how long the boundary will remain.','Planning around demolition access','Share equipment entrances and debris-removal routes. Windscreen can reduce visibility into the work and help with dust along the perimeter. It should be planned together with the fence supporting it.','Keeping a cleared lot enclosed','If a lot will remain closed for months, discuss post-driven chain link. Panels are useful where the layout or entrance needs to change. Richard can compare the installation work and flexibility of both systems.'),
'avon':('Avon','Commercial frontages that stay open during construction','For work along the US 36 corridor, the construction area may sit beside businesses that remain open. Send the project boundary and public access plan so the fence separates the work without closing needed entrances.','A fence that follows the phases','Panels and stands suit a frontage that changes as construction advances. Your crew can shift individual sections, and Fence Wizards can handle a larger relocation.','Schools and municipal properties','For a longer institutional project, consider the fixed boundary, pedestrian access, and gate locations together. Post-driven chain link can suit a stable perimeter where the ground accepts posts.'),
'brownsburg':('Brownsburg','Construction and event fencing in Hendricks County','Brownsburg projects include commercial construction, event grounds, and work along active town streets. We supply fence panels, driven chain link, windscreen, and barricades to match the job.','Event grounds and parking layouts','For event weekends, share the vendor areas, entrances, queues, and vehicle crossings. Setup and pickup can follow the event schedule, including evening load-out.','Street-facing construction','On a constrained frontage around an established business district, identify the pedestrian route and unloading space. Portable panels with screen can suit a changing work area, while longer fixed boundaries may suit driven fencing.'),
'columbus':('Columbus','Industrial work, public frontages, and restoration','Fence Wizards serves commercial and industrial projects in Columbus from Greenwood. Include the site address, ground conditions, and any limits on delivery access when requesting a quote.','Enclosing a working industrial site','A plant project may need contractor storage separated from ongoing operations. Tell us which entrances remain in use and which sides of the fence will stay fixed throughout the project.','Downtown work and urgent closures','Screen can reduce the view into a street-facing construction area. For storm or flood-related restoration, call with the location and the area that needs to be secured so Richard can discuss timing.'),
'franklin':('Franklin','Temporary fencing close to our Greenwood base','Franklin is in Johnson County, close to the Fence Wizards yard. We provide fencing for commercial construction, institutional projects, events, and restoration work.','Campus and public-facing projects','Where work meets students or the general public, share the pedestrian routes and vehicle access points. Ground conditions and the length of the job help determine whether panels or a driven line fit the plan.','Work beside open businesses','For a downtown frontage, allow for shop entrances and deliveries. Screen can reduce the view into the site, while portable panels make a changing work boundary easier to adjust. Call Richard about urgent setup or changes to an existing job.'),
'greenwood':('Greenwood','Our home base in Johnson County','Richard grew up in Greenwood, and this is where the company and trucks are based. We work with contractors, businesses, and event organizers throughout the city and the south side of the metro.','Commercial sites along US 31 and SR 135','Retail construction and development can require a perimeter that changes during the job. Panels and stands allow individual sections to move when access changes. Share the delivery route and planned phases when requesting the quote.','Local service when the plan changes','Fence Wizards is close by when a gate needs moving or a run needs extending. General contractors receive same-day site-change service. For a new urgent installation, call Richard to confirm the time and equipment available.'),
'lafayette':('Lafayette','Longer industrial and institutional perimeters','Lafayette and West Lafayette are toward the northwest edge of our coverage. We serve industrial, commercial, and institutional projects and include travel in the project quote.','Plan the full run before installation','Long perimeters benefit from clear gate locations, an estimate of the footage, and information about the surface. A fixed line may suit post-driven chain link, while changing entrances can use portable panels.','Coordinate the delivery and access','Share the installation window and any restrictions on where the truck can unload. A complete site plan helps organize work farther from Greenwood and reduces the need to revisit unresolved details.'),
'muncie':('Muncie','Institutional projects, redevelopment, and events','Fence Wizards serves Muncie and surrounding commercial projects. Our fencing has been used at Ball State University sites; the university was the end user rather than necessarily our direct customer.','Redevelopment and longer closures','For demolition or a building that must stay closed during redevelopment, discuss the expected duration and the access needed by crews. Post-driven fencing and screen may suit a longer fixed boundary.','Construction and events on the same grounds','A site can change use between a construction phase and an event. Panels, barricades, and screen can serve different areas. Include both schedules when the work and event setup need to be coordinated.'),
'plainfield':('Plainfield','Warehouse boundaries and delivery access','Plainfield distribution and commercial sites can need long fence runs with frequent truck access. Start the plan with the entrances, turning paths, and storage areas.','Make the gates work for the trucks','Gate width and placement should follow the vehicles using the site. Show Richard where trailers approach, turn, and wait so the fence layout supports deliveries.','Protecting material and equipment areas','A temporary enclosure can separate a staging area from the rest of a busy property. Panels suit an area that changes; post-driven fencing may suit a longer fixed boundary. Screen is available where reducing visibility is useful.'),
'richmond':('Richmond','Commercial fencing toward the eastern edge of our coverage','Richmond is near the eastern edge of our published service area. Send the full address so Richard can confirm scheduling and account for the travel in your quote.','Longer industrial and commercial projects','For a plant expansion or a long construction phase, a driven perimeter can stay in place while the work continues. Panels may be useful where the delivery entrance needs to change.','Coordinate deliveries from the start','Explain the approach your trucks use and how equipment will enter the property. If the project is beyond Richmond or over the state line, check coverage directly rather than assuming it is included.'),
'speedway':('Speedway','Event footprints, queues, and temporary access','Race-season activity and other events in Speedway can require temporary boundaries on a tight schedule. We supply panels, windscreen, and barricades for event organizers and commercial projects.','Start with entrances and crossings','Send the hospitality areas, vendor rows, queue lengths, and vehicle crossings on the event plan. Barricades can guide people while panels define the larger perimeter.','Sponsor graphics and pickup','Printed windscreen can display sponsor or event graphics along the run. Include the artwork requirements and production schedule early. Fencing can be removed when the event ends, with removal included in the quote.'),
'terre-haute':('Terre Haute','Planned installations at the western edge of our area','We serve Terre Haute at the western edge of our coverage. Travel is part of the quote, and a clear scope helps organize an installation farther from Greenwood.','Know the ground and access','Fill, rock, soft ground, and hard surfaces affect the choice between driven posts and weighted stands. Tell Richard about known site conditions before installation.','Make the trip count','Send the footage, fence height, gates, and expected rental duration together. For emergency work, call to confirm availability. For scheduled projects, advance notice helps coordinate the crew, material, and truck.'),
'westfield':('Westfield','Tournament schedules and construction that changes','Westfield event grounds and commercial projects have different demands on a temporary perimeter. Include the schedule and expected changes to the layout when discussing your job.','Tournament and event footprints','On a large sports-event footprint, entrances, vendor areas, and parking routes need to be planned together. Long panel runs and barricades can be set around the load-in and load-out schedule.','Construction phases along busy corridors','Portable panels suit areas where access moves as the work progresses. A fixed boundary may be better served by a driven line. Tell Richard which portions of the site will change and which will stay closed.'),
'zionsville':('Zionsville','Tight frontages, paved surfaces, and screened work areas','A project beside an active Zionsville street needs a plan for both the work and the people passing it. Share surface conditions and truck access before selecting the fence.','Protecting finished surfaces','Panels sit in weighted stands without driving posts into brick or paving. They are useful on a constrained village frontage where a permanent surface needs to stay intact.','Planning the unloading space','Narrow access may mean material cannot unload directly beside the run. Tell Richard where the truck can stop and how far the panels need to be moved. Plain or printed windscreen can provide privacy along the public-facing edge.')}
